### ISSUE TITLE
Laravel Flysystem adapter integration

### ISSUE THREAD

**Issue by nagi1** [cubiclesoft/efss#1]
Hi, I'm amazed of how you created a whole File system implementation using php!!! 

I'm building a DMS (Document Management system) and I'm considering using EFSS as a base for the encryption system.

The problem that I'm using Laravel which is very opinionated!

How do you suggest that I create Adapter from EFSS to Laravel flysystem?

https://flysystem.thephpleague.com/v1/docs/adapter/local/

https://flysystem.thephpleague.com/v1/docs/advanced/creating-an-adapter/

**Comment by cubiclesoft** [comment]
Just so you know, I don't use EFSS for anything serious these days due to running into major performance problems with EFSS as a backup system - I still use Cloud Backup extensively and is superior in design to both EFSS and delta-based backup systems.  The EFSS file system can become seriously fragmented if a lot of variable updates and deletions occur.  If you are just doing inserts and reads and the occasional update/delete, then it probably won't be an issue.  I started writing a C++ port at one point too with the goal of interfacing with [FUSE](https://en.wikipedia.org/wiki/Filesystem_in_Userspace) until I discovered the performance problems.

I've only ever worked with one Laravel app and those links don't provide enough hints to me to provide general guidance.  I suggest looking at the source code of both Local and ZipArchive as the basis for your integration.  You are better off asking the Flysystem devs about creating custom adapters.  A layer over this library that acts as glue between Flysystem and EFSS is recommended.  I'm going to guess that PHP file streams are the tricky part.  You can create fake PHP streams with `php://temp` as the filename.

**Comment by nagi1** [comment]
Thank you for taking the time to read the issue and visit the links 😍

I don't have problem with backup or particularly, I think I'll be fine just backup the whole EFSS .dat file into another server!

As for the flysystem integration I actually start experimenting with building an adapter for EFSS. Like you've mentioned php streams are the tricky part. Plus there's a lot of the undocumented functions on the EFSS class that make extremely hard for me when/where to use it!

For example: `write` vs `writeStream`, how EFSS handle write or write streams?

If you have time here's my untested tinkering with building an adapter for EFSS using `Local` and `ZipArchive` as a base for my integration.

Finally if you have any suggestions for alternatives I would be thankfull.

BTW I admire your work.

```php
<?php

namespace Nagi\FlySystemEfss;

use CubicleSoft\EFSS;
use CubicleSoft\EFSS_DirEntry_DirFile;
use finfo as Finfo;
use League\Flysystem\Adapter\AbstractAdapter;
use League\Flysystem\Config;
use League\Flysystem\Util;

// Flysystem standard array ['type' => 'file', 'path' => $path, 'contents' => '', 'stream' => 'resource', 'visibility' => 'public or private', 'timestamp' => 'integer modified time'];

class EfssAdapter extends AbstractAdapter
{
    private EFSS $efss;

    protected static $permissions = [
        'file' => [
            'public' => 0644,
            'private' => 0600,
        ],
        'dir' => [
            'public' => 0755,
            'private' => 0700,
        ],
    ];

    public function __construct()
    {
        $this->efss = new EFSS();
    }

    /**
     * {@inheritdoc}
     */
    public function write($path, $contents, Config $config)
    {
        $result = $this->efss->file_put_contents($path, $contents);

        if ($result['success']) {
            if ($visibility = $config->get('visibility')) {
                $this->setVisibility($path, $visibility);
            }

            return ['type' => 'file', 'path' => $path, 'contents' => '', 'stream' => 'resource', 'visibility' => $visibility];
        }

        return false;
    }

    /**
     * {@inheritdoc}
     */
    public function writeStream($path, $resource, Config $config)
    {
        return $this->write($path, $resource, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function update($path, $contents, Config $config)
    {
        return $this->write($path, $contents, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function updateStream($path, $resource, Config $config)
    {
        return $this->write($path, $resource, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function rename($path, $newpath)
    {
        $result = $this->efss->rename($path, $newpath);

        return $result['success'];
    }

    /**
     * {@inheritdoc}
     */
    public function copy($path, $newpath)
    {
        $result = $this->efss->copy($path, $newpath);

        return $result['success'];
    }

    /**
     * {@inheritdoc}
     */
    public function delete($path)
    {
        $result = $this->efss->unlink($path);

        return $result['success'];
    }

    /**
     * {@inheritdoc}
     */
    public function deleteDir($dirname)
    {
        $result = $this->efss->rmdir($dirname, true);

        return $result['success'];
    }

    /**
     * {@inheritdoc}
     */
    public function createDir($dirname, Config $config)
    {
        $visibility = $config->get('visibility', 'public');
        $result = $this->efss->mkdir($dirname, static::$permissions['dir'][$visibility]);

        if ($result['success']) {
            return ['type' => 'dir', 'path' => $dirname, 'visibility' => $visibility];
        }

        return false;
    }

    /**
     * {@inheritdoc}
     */
    public function setVisibility($path, $visibility)
    {
        $type = $this->efss->is_dir($path) ? 'dir' : 'file';

        $result = $this->efss->chmod($path, static::$permissions[$type][$visibility]);

        if ($result['success'] === false) {
            return false;
        }

        return compact('path', 'visibility');
    }

    /**
     * {@inheritdoc}
     */
    public function has($path)
    {
        $result = $this->efss->file_exists($path);

        return $result['success'];
    }

    /**
     * {@inheritdoc}
     */
    public function read($path)
    {
        $result = $this->efss->file_get_contents($path);

        if ($result['success'] === false) {
            return false;
        }

        return ['type' => 'file', 'path' => $path, 'contents' => $result['data']];
    }

    /**
     * {@inheritdoc}
     */
    public function readStream($path)
    {
        return $this->read($path);
    }

    /**
     * {@inheritdoc}
     */
    public function listContents($directory = '', $recursive = false)
    {
        return $this->efss->d;
    }

    /**
     * {@inheritdoc}
     */
    public function getMetadata($path)
    {
        $result = $this->efss->GetFileInfo($path);

        if (! $result['success']) {
            return false;
        }

        return $this->normalizeFileInfo($result['fileinfo'], $path);
    }

    /**
     * Normalize the file info.
     */
    protected function normalizeFileInfo(EFSS_DirEntry_DirFile $file, string $path)
    {
        $normalized = [
            'type' => $this->getType($file->type),
            'path' => $path,
        ];

        $normalized['timestamp'] = $file->created;

        if ($normalized['type'] === 'file') {
            $normalized['size'] = $file->fullsize;
        }

        return $normalized;
    }

    protected function getType(string $type)
    {
        return $type === EFSS_DIRTYPE_DIR ? 'dir' : 'file';
    }

    /**
     * {@inheritdoc}
     */
    public function getSize($path)
    {
        return $this->getMetadata($path);
    }

    /**
     * {@inheritdoc}
     */
    public function getMimetype($path)
    {
        $finfo = new Finfo(FILEINFO_MIME_TYPE);
        $mimetype = $finfo->file($path);

        if (in_array($mimetype, ['application/octet-stream', 'inode/x-empty', 'application/x-empty'])) {
            $mimetype = Util\MimeType::detectByFilename($path);
        }

        return ['path' => $path, 'type' => 'file', 'mimetype' => $mimetype];
    }

    /**
     * {@inheritdoc}
     */
    public function getTimestamp($path)
    {
        return $this->getMetadata($path);
    }

    /**
     * {@inheritdoc}
     */
    public function getVisibility($path)
    {
        return 'public';
    }
}

```

**Comment by cubiclesoft** [comment]
By backup, I meant that EFSS was the _basis_ of a backup system at one point in time.  [Cloud Backup](https://github.com/cubiclesoft/cloud-backup) supersedes that use-case.

As to documentation, the `docs` directory and the test suite and various applications at the root have a variety of documentation and example usage.  I don't really know of any alternatives for PHP.  There's probably something available in the FUSE universe if you want something more native to the host OS (i.e. to PHP it would appear as a local mount).

If your code works, then that's good enough.  I suspect the stream functions are for handling large files but the way Flysystem works looks like it won't hand over data to the function in chunks, so you're probably stuck with using a lot of RAM when using Flysystem with large files.  If I recall correctly, EFSS `file_put_contents()` can optimize how it writes the data to disk (versus fopen()/fwrite()/fclose()) while `file_get_contents()` is a convenience function.

**Comment by nagi1** [comment]
```php
    public function writeStream($path, $resource, Config $config)
    {
        return $this->write($path, $resource, $config);
    }
```

I think this function will hand over the data in chunks since it accepts a recourse as the second argument.

I just don't know if the EFSS have functions to accept data as chucks or using ram?

**Comment by cubiclesoft** [comment]
If `$config` passes custom information that lets continuation of writes to happen, then that's how you can maintain state between calls.  Otherwise, I'm not sure and you'd have to ask the Flysystem folks about it.  Their documentation on making a new adapter seems rather limited.

EFSS has fopen()/fwrite()/fclose() calls for working with larger files.

From https://github.com/cubiclesoft/efss/blob/master/docs/efss.md:

> The bulk of the functionality is nearly identical to PHP's file and directory functions with some limitations here and there and a few extra features here and there. The only major difference between PHP and EFSS is the return value of each function, which is always a standard information array in the EFSS class. Every function in the EFSS class is tested in the test suite, so there is usually at least one working example.

**Comment by cubiclesoft** [comment]
Since this is mostly just a question rather than a bug in the software or documentation, I'm going to close this issue.
